### ISSUE TITLE
Erreur après première installation

### ISSUE THREAD

**Issue by Naarx** [Gwemox/plugin.video.replayksys#1]
Kodi Krypton (17.6) sous raspbian
Après avoir installé et activé l'addon, lors du premier lancement du replay il ya une erreur:

> IOError: (2, 'No such file or directory', '/home/pi/.kodi/userdata/addon_data/plugin.video.replayksys/.jwt') 

En créant le repertoire "plugin.video.replayksys/.jwt", le problème disparait.

**A noter**: j'ai un répertoire ".jwt" qui a été créé sous "/home/pi/.kodi/userdata/addon_data" (probablement a l'installation)

**Comment by Gwemox** [comment]
Juste pour information : .jwt n'est pas un répertoire mais un fichier.

**Comment by Naarx** [comment]
J'ai aussi installé sous Kodi 17.6 LibreElec, je n'ai pas eu le problème (.jwt était au bon endroit)

La seule différence par rapport à l'installation Raspbian est que j'ai renseigné les identifiants dans "Settings" de l'addon avant de l'enregistrer sur le site.

**Comment by Gwemox** [comment]
J'ai oublié de préciser dans le post. Il est strictement inutile de renseigner ses identifiants dans le menu paramètres. 

C'est tout le but de l'authentification par code.

**Comment by Naarx** [comment]
> 
> 
> Juste pour information : .jwt n'est pas un répertoire mais un fichier.

Oui, mon erreur.
C'est en créant le répertoire "plugin.video.replayksys/" que le problème a du se résoudre.
