### ISSUE TITLE
Erreur en utilisant la sélection par catégorie

### ISSUE THREAD

**Issue by Naarx** [Gwemox/plugin.video.replayksys#2]
Kodi 17.6 sous Raspian

Pour le choix d'un replay en utilisant les catégories, on peut naviguer dans les répertoires jusqu'à ce que l'addon indique une erreur. Ci-dessous le log:

[Kodi-Category-Log.txt](https://github.com/Gwemox/plugin.video.replayksys/files/2930271/Kodi-Category-Log.txt)

**Comment by Gwemox** [comment]
Possible de me donner le chemin de catégories exacte qui produit ce bug. 
Il manque title dans le retour EPG de KTV.

**Comment by Naarx** [comment]
J'ai reproduit le bug avec:
Catégories --> Jeunesse --> Dessin Animé

Le Log est le suivant:
[Kodi-Category1-Log.txt](https://github.com/Gwemox/plugin.video.replayksys/files/2930712/Kodi-Category1-Log.txt)

**Comment by Gwemox** [comment]
Corrigé 2bb1ff7

Disponible dans la prochaine version mineure.
